### ISSUE TITLE
CHECK with message doesn't work

### ISSUE THREAD

**Issue by GibbOne** [jasmcaus/tau#21]
First of all I'd like to thank @jasmcaus for this useful library.

So, I found out a little problem with custom failure message.
According to [documentation](https://github.com/jasmcaus/tau/blob/dev/docs/tau-primer.md#adding-custom-failure-messages) it's enough to add a further parameter. But If I add a parameter, the check never fails.

Below an example.

``` C
TEST(TAU, ItShouldFailWithMessage)
{
    CHECK(0);                           // this check fails correctly.
    CHECK(0, "It should FAIL");         // this check doesn't fail.
}
```

Am i missing something?

**Comment by jasmcaus** [comment]
@GibbOne I ran this locally, and it seems to work:

![image](https://user-images.githubusercontent.com/61184127/159928177-181cbf0e-8aed-4a8d-bf1f-445ecd03159b.png)

Try this in a test file:
```c
#include <tau/tau.h>
TAU_MAIN()

TEST(TAU, ItShouldFailWithMessage)
{
    CHECK(0);                           // this check fails correctly.
    CHECK(0, "It should FAIL");         // this check doesn't fail.
}
```

**Comment by GibbOne** [comment]
@jasmcaus if I use `gcc` it works like you did. But if I use MSVC, it doesn't.

![image](https://user-images.githubusercontent.com/12271500/160743926-ddb45123-8a89-416b-bf31-acadf6f27ddd.png)

(note missing message)

**Comment by jasmcaus** [comment]
@GibbOne See [this](https://github.com/jasmcaus/tau/actions/runs/2062619279). Only MSVC 2017 seems to fail. Not sure why. I don't have a Windows machine w/ me so it's quite hard for me to explore this. Would you mind taking a look and opening a PR with your changes?

**Comment by jasmcaus** [comment]
@matu3ba maybe you could have a look at this as well?

**Comment by matu3ba** [comment]
Let me spin up Windows in a WM to see, if I can reproduce.
```txt
// file t1.c
#include <tau/tau.h>
TAU_MAIN()

TEST(TAU, ItShouldFailWithMessage)
{
    CHECK(0);                           // this check fails correctly.
    //CHECK(0, "It should FAIL");         // this check doesn't fail.
}

// file t2.c
#include <tau/tau.h>
TAU_MAIN()

TEST(TAU, ItShouldFailWithMessage)
{
    //CHECK(0);                           // this check fails correctly.
    CHECK(0, "It should FAIL");         // this check doesn't fail.
}

// windows cmds:
// cl /I . t1.c -o t1
// cl /I . t2.c -o t2
// linux (works)
// gcc -I . test.c -o t1 && ./t1
// gcc -I . test.c -o t2 && ./t2
```

**Comment by matu3ba** [comment]
@GibbOne Please always provide version numbers for the compiler version.

On the latest? release 19.13.31105 I get with `cl /I tau t1.c` with t1.c having the following content:
```c
// file t1.c
#include <tau/tau.h>
TAU_MAIN()

TEST(TAU, ItShouldFailWithMessage)
{
    CHECK(0);      // this check fails correctly.
    //CHECK(0, "It should FAIL");           // this check doesn't fail.
}
```
the following error:
```txt
tau\tau/misc.h(34): fatal error C1083: Cannot open include fils: 'inttypes.h': No such file or directory.
```

So to me it looks like tau is broken on MSVC.

**Comment by GibbOne** [comment]
@matu3ba I already showed MSVC compiler version on my last post. Look at picture of console.

**Comment by matu3ba** [comment]
@GibbOne My bad.

At least this post indicates that Microsoft only guarantees compatibility via their libraries.
https://stackoverflow.com/questions/41975672/abi-compatibility-of-visual-studio-c-libraries

A proper fix would probably require https://stackoverflow.com/questions/9233118/library-abi-compatibility-between-versions-of-visual-studio with https://github.com/lvc/abi-compliance-checker to figure out what is broken,
since unfortunately Microsoft does not generate reports what stuff they broke how and when.

**Comment by GibbOne** [comment]
I solved by adding `/Zc:preprocessor` compiler option. 

See https://stackoverflow.com/a/5134656/6539880 and https://docs.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170.
