### ISSUE TITLE
Primer doc does not match code

### ISSUE THREAD

**Issue by pedro-w** [jasmcaus/tau#5]
In the primer doc there is [a mention](https://github.com/jasmcaus/tau/blame/dev/docs/tau-primer.md#L73) of `REQUIRE_STRNNEQ` and `CHECK_STRNNEQ`
but I think, in the code they're actually `REQUIRE_STRNE` / `REQUIRE_STRNNE` and `CHECK_STRNE` /  `CHECK_STRNNE`

**Comment by jasmcaus** [comment]
Thanks for pointing this out!
